"""add organizations deals and pipeline_stages tables

Revision ID: 022034d7bc31
Revises: 8dcb6880a52b
Create Date: 2025-10-24 14:26:16.412140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022034d7bc31'
down_revision: Union[str, None] = '8dcb6880a52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('deals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_company', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('deal_size', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stage', sa.Enum('sourcing', 'evaluation', 'due_diligence', 'negotiation', 'closing', 'won', 'lost', name='dealstage', native_enum=False, length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deals_archived', 'deals', ['is_archived'], unique=False)
    op.create_index('idx_deals_created_at', 'deals', ['created_at'], unique=False)
    op.create_index('idx_deals_organization_id', 'deals', ['organization_id'], unique=False)
    op.create_index('idx_deals_owner_id', 'deals', ['owner_id'], unique=False)
    op.create_index('idx_deals_stage', 'deals', ['stage'], unique=False)
    op.create_index(op.f('ix_deals_organization_id'), 'deals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_deals_owner_id'), 'deals', ['owner_id'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_stages_order', 'pipeline_stages', ['order'], unique=False)
    op.create_index('idx_pipeline_stages_organization_id', 'pipeline_stages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_organization_id'), 'pipeline_stages', ['organization_id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_constraint('users_clerk_user_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_clerk_user_id_key', 'users', ['clerk_user_id'])
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'organization_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'solo'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_pipeline_stages_organization_id'), table_name='pipeline_stages')
    op.drop_index('idx_pipeline_stages_organization_id', table_name='pipeline_stages')
    op.drop_index('idx_pipeline_stages_order', table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_deals_owner_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_organization_id'), table_name='deals')
    op.drop_index('idx_deals_stage', table_name='deals')
    op.drop_index('idx_deals_owner_id', table_name='deals')
    op.drop_index('idx_deals_organization_id', table_name='deals')
    op.drop_index('idx_deals_created_at', table_name='deals')
    op.drop_index('idx_deals_archived', table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
