"""Add deals and pipeline_stages tables

Revision ID: 36b3e62b4148
Revises: 8dcb6880a52b
Create Date: 2025-10-24 14:57:38.874177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '36b3e62b4148'
down_revision: Union[str, None] = '8dcb6880a52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _get_inspector():
    return inspect(op.get_bind())


def _table_exists(table_name: str, inspector=None) -> bool:
    inspector = inspector or _get_inspector()
    return inspector.has_table(table_name)


def _column_exists(table_name: str, column_name: str, inspector=None) -> bool:
    inspector = inspector or _get_inspector()
    if not inspector.has_table(table_name):
        return False
    return any(column["name"] == column_name for column in inspector.get_columns(table_name))


def _index_exists(table_name: str, index_name: str, inspector=None) -> bool:
    inspector = inspector or _get_inspector()
    if not inspector.has_table(table_name):
        return False
    return any(index["name"] == index_name for index in inspector.get_indexes(table_name))


def _unique_constraint_exists(table_name: str, constraint_name: str, inspector=None) -> bool:
    inspector = inspector or _get_inspector()
    if not inspector.has_table(table_name):
        return False
    return any(constraint["name"] == constraint_name for constraint in inspector.get_unique_constraints(table_name))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CRITICAL FIX: Convert users table columns to String(36) FIRST
    # before creating tables with FKs to users.id
    # This ensures FK type constraints match on PostgreSQL

    # STEP 1: Modify users table (convert UUID to String(36))
    inspector = _get_inspector()
    if not _column_exists('users', 'deleted_at', inspector):
        op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               postgresql_using='id::text')
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True,
               postgresql_using='organization_id::text')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    if _index_exists('users', 'ix_users_email', inspector):
        op.drop_index('ix_users_email', table_name='users')
    if _unique_constraint_exists('users', 'users_clerk_user_id_key', inspector):
        op.drop_constraint('users_clerk_user_id_key', 'users', type_='unique')

    # STEP 2: Create organizations table (now users.organization_id is String(36))
    if not _table_exists('organizations', inspector):
        op.create_table('organizations',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('subscription_tier', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        inspector = _get_inspector()
    if not _index_exists('organizations', op.f('ix_organizations_slug'), inspector):
        op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)

    # STEP 3: Create deals table (FK to users.id now matches String(36))
    if not _table_exists('deals', inspector):
        op.create_table('deals',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('organization_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('target_company', sa.String(length=255), nullable=False),
        sa.Column('industry', sa.String(length=100), nullable=True),
        sa.Column('deal_size', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('stage', sa.Enum('sourcing', 'evaluation', 'due_diligence', 'negotiation', 'closing', 'won', 'lost', name='dealstage', native_enum=False, length=50), nullable=False),
        sa.Column('owner_id', sa.String(length=36), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_archived', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        inspector = _get_inspector()
    for index_name, columns in [
        ('idx_deals_archived', ['is_archived']),
        ('idx_deals_created_at', ['created_at']),
        ('idx_deals_organization_id', ['organization_id']),
        ('idx_deals_owner_id', ['owner_id']),
        ('idx_deals_stage', ['stage']),
    ]:
        if not _index_exists('deals', index_name, inspector):
            op.create_index(index_name, 'deals', columns, unique=False)
    if not _index_exists('deals', op.f('ix_deals_organization_id'), inspector):
        op.create_index(op.f('ix_deals_organization_id'), 'deals', ['organization_id'], unique=False)
    if not _index_exists('deals', op.f('ix_deals_owner_id'), inspector):
        op.create_index(op.f('ix_deals_owner_id'), 'deals', ['owner_id'], unique=False)

    # STEP 4: Create pipeline_stages table
    if not _table_exists('pipeline_stages', inspector):
        op.create_table('pipeline_stages',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('organization_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('order', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('color', sa.String(length=7), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        inspector = _get_inspector()
    if not _index_exists('pipeline_stages', 'idx_pipeline_stages_order', inspector):
        op.create_index('idx_pipeline_stages_order', 'pipeline_stages', ['order'], unique=False)
    if not _index_exists('pipeline_stages', 'idx_pipeline_stages_organization_id', inspector):
        op.create_index('idx_pipeline_stages_organization_id', 'pipeline_stages', ['organization_id'], unique=False)
    if not _index_exists('pipeline_stages', op.f('ix_pipeline_stages_organization_id'), inspector):
        op.create_index(op.f('ix_pipeline_stages_organization_id'), 'pipeline_stages', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse operations in opposite order of upgrade()

    # STEP 1: Drop pipeline_stages table
    op.drop_index(op.f('ix_pipeline_stages_organization_id'), table_name='pipeline_stages')
    op.drop_index('idx_pipeline_stages_organization_id', table_name='pipeline_stages')
    op.drop_index('idx_pipeline_stages_order', table_name='pipeline_stages')
    op.drop_table('pipeline_stages')

    # STEP 2: Drop deals table
    op.drop_index(op.f('ix_deals_owner_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_organization_id'), table_name='deals')
    op.drop_index('idx_deals_stage', table_name='deals')
    op.drop_index('idx_deals_owner_id', table_name='deals')
    op.drop_index('idx_deals_organization_id', table_name='deals')
    op.drop_index('idx_deals_created_at', table_name='deals')
    op.drop_index('idx_deals_archived', table_name='deals')
    op.drop_table('deals')

    # STEP 3: Drop organizations table
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')

    # STEP 4: Restore users table columns (convert back to UUID)
    op.create_unique_constraint('users_clerk_user_id_key', 'users', ['clerk_user_id'])
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'organization_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='organization_id::uuid')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'solo'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    # ### end Alembic commands ###