"""add document AI suggestions and version history tables with GUID

Revision ID: 774225e563ca
Revises: b354d12d1e7d
Create Date: 2025-11-13 10:14:13.253911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
ORGANIZATION_TYPE = sa.String(length=36)
from sqlalchemy.dialects import postgresql
from app.db.base import GUID

# revision identifiers, used by Alembic.
revision: str = '774225e563ca'
down_revision: Union[str, None] = 'b354d12d1e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CRITICAL: Ensure users.id is VARCHAR(36) before creating foreign keys
    # Migration 36b3e62b4148 should have converted users.id from UUID to VARCHAR(36)
    # If it didn't, we MUST convert it here before creating new tables
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        # Force conversion: Drop all FKs, convert users.id and FK columns, then proceed
        # Use information_schema which is more reliable than pg_type
        op.execute("""
            DO $$ 
            DECLARE
                col_type text;
                fk_rec record;
            BEGIN
                -- Check if users.id is UUID using information_schema
                SELECT data_type INTO col_type
                FROM information_schema.columns
                WHERE table_schema = 'public'
                AND table_name = 'users'
                AND column_name = 'id';
                
                -- If users.id is UUID, convert everything
                IF col_type = 'uuid' THEN
                    -- Step 1: Drop all FK constraints that reference users.id
                    FOR fk_rec IN 
                        SELECT 
                            con.conname AS constraint_name,
                            con.conrelid::regclass::text AS table_name,
                            a.attname AS column_name
                        FROM pg_constraint con
                        JOIN pg_attribute a ON a.attrelid = con.conrelid 
                            AND a.attnum = ANY(con.conkey)
                        WHERE con.confrelid = 'users'::regclass
                        AND con.contype = 'f'
                        AND con.conrelid != 'users'::regclass
                    LOOP
                        -- Drop FK constraint
                        EXECUTE format('ALTER TABLE %s DROP CONSTRAINT IF EXISTS %I CASCADE', 
                            fk_rec.table_name, fk_rec.constraint_name);
                        
                        -- Convert FK column to VARCHAR(36)
                        BEGIN
                            EXECUTE format('ALTER TABLE %s ALTER COLUMN %I TYPE VARCHAR(36) USING %I::text',
                                fk_rec.table_name, fk_rec.column_name, fk_rec.column_name);
                        EXCEPTION
                            WHEN OTHERS THEN
                                -- Column might already be VARCHAR, continue
                                NULL;
                        END;
                    END LOOP;
                    
                    -- Step 2: Convert users.id to VARCHAR(36) (CRITICAL)
                    ALTER TABLE users ALTER COLUMN id TYPE VARCHAR(36) USING id::text;
                    
                    -- Step 3: Convert users.organization_id if it exists and is UUID
                    BEGIN
                        SELECT data_type INTO col_type
                        FROM information_schema.columns
                        WHERE table_schema = 'public'
                        AND table_name = 'users'
                        AND column_name = 'organization_id';
                        
                        IF col_type = 'uuid' THEN
                            ALTER TABLE users 
                            ALTER COLUMN organization_id TYPE VARCHAR(36) USING organization_id::text;
                        END IF;
                    EXCEPTION
                        WHEN OTHERS THEN
                            NULL;
                    END;
                END IF;
                
                -- Also check and convert organizations.id if it's UUID (independent of users.id)
                -- First check if organizations table exists
                IF EXISTS (
                    SELECT 1 FROM information_schema.tables
                    WHERE table_schema = 'public'
                    AND table_name = 'organizations'
                ) THEN
                    SELECT data_type INTO col_type
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                    AND table_name = 'organizations'
                    AND column_name = 'id';
                    
                    IF col_type = 'uuid' THEN
                        -- Step 1: Drop all FK constraints that reference organizations.id
                        FOR fk_rec IN
                            SELECT
                                con.conname AS constraint_name,
                                con.conrelid::regclass::text AS table_name,
                                a.attname AS column_name
                            FROM pg_constraint con
                            JOIN pg_attribute a ON a.attrelid = con.conrelid
                                AND a.attnum = ANY(con.conkey)
                            WHERE con.confrelid = 'organizations'::regclass
                            AND con.contype = 'f'
                            AND con.conrelid != 'organizations'::regclass
                        LOOP
                            -- Drop FK constraint
                            EXECUTE format('ALTER TABLE %s DROP CONSTRAINT IF EXISTS %I CASCADE',
                                fk_rec.table_name, fk_rec.constraint_name);

                            -- Convert FK column to VARCHAR(36)
                            BEGIN
                                EXECUTE format('ALTER TABLE %s ALTER COLUMN %I TYPE VARCHAR(36) USING %I::text',
                                    fk_rec.table_name, fk_rec.column_name, fk_rec.column_name);
                            EXCEPTION
                                WHEN OTHERS THEN
                                    -- Column might already be VARCHAR, continue
                                    NULL;
                            END;
                        END LOOP;

                        -- Step 2: Convert organizations.id to VARCHAR(36) (CRITICAL)
                        ALTER TABLE organizations ALTER COLUMN id TYPE VARCHAR(36) USING id::text;
                    END IF;
                END IF;  -- End organizations table exists check
            END $$;
        """)
    
    # Always use VARCHAR(36) for user foreign keys (matching converted users.id type)
    # The conversion above ensures users.id is VARCHAR(36), so FKs must be VARCHAR(36) too
    op.create_table('community_follows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('follower_user_id', sa.String(length=36), nullable=False),
    sa.Column('following_user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['follower_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_community_follows_follower', 'community_follows', ['follower_user_id'], unique=False)
    op.create_index('idx_community_follows_following', 'community_follows', ['following_user_id'], unique=False)
    op.create_index('idx_community_follows_org', 'community_follows', ['organization_id'], unique=False)
    op.create_index('idx_community_follows_unique', 'community_follows', ['follower_user_id', 'following_user_id'], unique=True)
    op.create_index(op.f('ix_community_follows_follower_user_id'), 'community_follows', ['follower_user_id'], unique=False)
    op.create_index(op.f('ix_community_follows_following_user_id'), 'community_follows', ['following_user_id'], unique=False)
    op.create_index(op.f('ix_community_follows_organization_id'), 'community_follows', ['organization_id'], unique=False)
    op.create_table('community_moderation_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.Enum('post', 'comment', name='targettype', native_enum=False, length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.Enum('approve', 'reject', 'flag', 'delete', 'unflag', name='moderationactiontype', native_enum=False, length=32), nullable=False),
    sa.Column('moderator_user_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['moderator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_community_moderation_created', 'community_moderation_actions', ['created_at'], unique=False)
    op.create_index('idx_community_moderation_moderator', 'community_moderation_actions', ['moderator_user_id'], unique=False)
    op.create_index('idx_community_moderation_target', 'community_moderation_actions', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_community_moderation_actions_moderator_user_id'), 'community_moderation_actions', ['moderator_user_id'], unique=False)
    op.create_index(op.f('ix_community_moderation_actions_target_id'), 'community_moderation_actions', ['target_id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('general', 'deals', 'insights', 'qa', 'networking', name='postcategory', native_enum=False, length=32), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', 'flagged', name='poststatus', native_enum=False, length=32), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_community_posts_author', 'community_posts', ['author_user_id'], unique=False)
    op.create_index('idx_community_posts_category', 'community_posts', ['category'], unique=False)
    op.create_index('idx_community_posts_created', 'community_posts', ['created_at'], unique=False)
    op.create_index('idx_community_posts_org_id', 'community_posts', ['organization_id'], unique=False)
    op.create_index('idx_community_posts_status', 'community_posts', ['status'], unique=False)
    op.create_index(op.f('ix_community_posts_author_user_id'), 'community_posts', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_community_posts_organization_id'), 'community_posts', ['organization_id'], unique=False)
    op.create_table('community_reactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.Enum('post', 'comment', name='targettype', native_enum=False, length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reaction_type', sa.Enum('like', 'love', 'insightful', 'celebrate', name='reactiontype', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_community_reactions_target', 'community_reactions', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_community_reactions_unique', 'community_reactions', ['target_type', 'target_id', 'user_id', 'reaction_type'], unique=True)
    op.create_index('idx_community_reactions_user', 'community_reactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_community_reactions_target_id'), 'community_reactions', ['target_id'], unique=False)
    op.create_index(op.f('ix_community_reactions_user_id'), 'community_reactions', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('VIRTUAL', 'IN_PERSON', 'HYBRID', name='eventtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED', name='eventstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('virtual_link', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['community_comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_community_comments_author', 'community_comments', ['author_user_id'], unique=False)
    op.create_index('idx_community_comments_created', 'community_comments', ['created_at'], unique=False)
    op.create_index('idx_community_comments_parent', 'community_comments', ['parent_comment_id'], unique=False)
    op.create_index('idx_community_comments_post', 'community_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_comments_author_user_id'), 'community_comments', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_community_comments_parent_comment_id'), 'community_comments', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_community_comments_post_id'), 'community_comments', ['post_id'], unique=False)
    op.create_table('event_analytics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('total_registrations', sa.Integer(), nullable=True),
    sa.Column('total_attendees', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('session_metrics', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('virtual_link', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('speaker_name', sa.String(), nullable=True),
    sa.Column('speaker_bio', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('quantity_sold', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD_OUT', 'CANCELLED', name='ticketstatus'), nullable=False),
    sa.Column('sale_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_ai_suggestions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'APPLIED', name='suggestionstatus'), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['generated_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['generated_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('ticket_id', sa.String(length=36), nullable=True),
    sa.Column('attendee_name', sa.String(), nullable=False),
    sa.Column('attendee_email', sa.String(), nullable=False),
    sa.Column('attendee_phone', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'ATTENDED', 'NO_SHOW', name='registrationstatus'), nullable=False),
    sa.Column('checked_in', sa.Boolean(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('registered_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['event_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['event_tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_share_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('allow_download', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_share_links_document_id', 'document_share_links', ['document_id'], unique=False)
    op.create_index('idx_share_links_expires_at', 'document_share_links', ['expires_at'], unique=False)
    op.create_index('idx_share_links_org_id', 'document_share_links', ['organization_id'], unique=False)
    op.create_index('idx_share_links_token', 'document_share_links', ['share_token'], unique=False)
    op.create_index(op.f('ix_document_share_links_share_token'), 'document_share_links', ['share_token'], unique=True)
    op.drop_index('ix_contact_messages_created_at', table_name='contact_messages')
    op.drop_index('ix_contact_messages_email', table_name='contact_messages')
    op.drop_index('ix_contact_messages_id', table_name='contact_messages')
    op.drop_table('contact_messages')
    op.alter_column('admin_activities', 'amount',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_activities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_activities_id'), 'admin_activities', ['id'], unique=False)
    op.alter_column('admin_campaign_recipients', 'sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_campaign_recipients', 'opened',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_campaign_recipients', 'clicked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_campaign_recipients', 'bounced',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_admin_campaign_recipients_id'), 'admin_campaign_recipients', ['id'], unique=False)
    op.alter_column('admin_campaigns', 'status',
               existing_type=postgresql.ENUM('draft', 'scheduled', 'sending', 'sent', 'paused', 'cancelled', name='campaignstatus'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_campaigns', 'total_recipients',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_campaigns', 'sent_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_campaigns', 'opened_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_campaigns', 'clicked_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_campaigns_id'), 'admin_campaigns', ['id'], unique=False)
    op.alter_column('admin_collateral', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_collateral', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_collateral_id'), 'admin_collateral', ['id'], unique=False)
    op.alter_column('admin_collateral_usage', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_collateral_usage_id'), 'admin_collateral_usage', ['id'], unique=False)
    op.alter_column('admin_content_pieces', 'status',
               existing_type=postgresql.ENUM('idea', 'scripting', 'recording', 'editing', 'ready', 'published', name='contentstatus'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_content_pieces', 'views_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_content_pieces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_content_pieces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_content_pieces_id'), 'admin_content_pieces', ['id'], unique=False)
    op.alter_column('admin_content_scripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_content_scripts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_content_scripts_id'), 'admin_content_scripts', ['id'], unique=False)
    op.alter_column('admin_deals', 'stage',
               existing_type=postgresql.ENUM('discovery', 'qualification', 'proposal', 'negotiation', 'closing', 'won', 'lost', name='admindealstage'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_deals', 'probability',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_deals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_deals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_deals_id'), 'admin_deals', ['id'], unique=False)
    op.alter_column('admin_focus_sessions', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_focus_sessions', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_focus_sessions', 'interrupted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_focus_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_focus_sessions_id'), 'admin_focus_sessions', ['id'], unique=False)
    op.alter_column('admin_goals', 'target_discoveries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_goals', 'target_emails',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_goals', 'target_videos',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_goals', 'target_calls',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_goals_id'), 'admin_goals', ['id'], unique=False)
    op.alter_column('admin_lead_captures', 'synced_to_ghl',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_lead_captures', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_lead_captures_id'), 'admin_lead_captures', ['id'], unique=False)
    op.alter_column('admin_meetings', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_meetings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_meetings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_meetings_id'), 'admin_meetings', ['id'], unique=False)
    op.alter_column('admin_nudges', 'priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='nudgepriority'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_nudges', 'read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_nudges', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_nudges_id'), 'admin_nudges', ['id'], unique=False)
    op.alter_column('admin_prospects', 'status',
               existing_type=postgresql.ENUM('new', 'qualified', 'engaged', 'proposal', 'negotiation', 'closed_won', 'closed_lost', name='prospectstatus'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_prospects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_prospects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_prospects_id'), 'admin_prospects', ['id'], unique=False)
    op.alter_column('admin_scores', 'streak_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_scores', 'activities_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('admin_scores', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_admin_scores_id'), 'admin_scores', ['id'], unique=False)
    op.alter_column('blog_posts', 'author',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('blog_posts', 'published',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('blog_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('blog_posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('blog_posts', 'read_time_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('deal_matches', sa.Column('organization_id', sa.String(length=36), nullable=False if True else False))
    op.create_index(op.f('ix_deal_matches_organization_id'), 'deal_matches', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'deal_matches', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('document_questions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('document_templates', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('document_templates', 'variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               nullable=True)
    op.alter_column('document_templates', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'ARCHIVED', name='templatestatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('document_templates', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('document_templates', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('document_templates', 'created_by_user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('document_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('idx_document_templates_created_at', table_name='document_templates')
    op.drop_index('idx_document_templates_organization_id', table_name='document_templates')
    op.drop_index('idx_document_templates_status', table_name='document_templates')
    op.drop_index('idx_document_templates_template_type', table_name='document_templates')
    op.alter_column('generated_documents', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('generated_documents', 'template_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('generated_documents', 'variable_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               nullable=True)
    op.alter_column('generated_documents', 'status',
               existing_type=postgresql.ENUM('draft', 'generated', 'finalized', 'sent', name='documentstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('generated_documents', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('generated_documents', 'generated_by_user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('generated_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('idx_generated_documents_created_at', table_name='generated_documents')
    op.drop_index('idx_generated_documents_organization_id', table_name='generated_documents')
    op.drop_index('idx_generated_documents_status', table_name='generated_documents')
    op.drop_index('idx_generated_documents_template_id', table_name='generated_documents')
    op.alter_column('pipeline_template_stages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pipeline_template_stages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_pipeline_template_stages_order', table_name='pipeline_template_stages')
    op.drop_index('ix_pipeline_template_stages_template', table_name='pipeline_template_stages')
    op.create_index(op.f('ix_pipeline_template_stages_template_id'), 'pipeline_template_stages', ['template_id'], unique=False)
    op.alter_column('pipeline_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pipeline_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pipeline_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_pipeline_templates_org_default', table_name='pipeline_templates')
    op.create_index('idx_pipeline_templates_org_default', 'pipeline_templates', ['organization_id', 'is_default'], unique=False)
    op.create_index(op.f('ix_pipeline_templates_organization_id'), 'pipeline_templates', ['organization_id'], unique=False)
    op.alter_column('rbac_audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_rbac_audit_logs_action', table_name='rbac_audit_logs')
    op.drop_index('ix_rbac_audit_logs_actor', table_name='rbac_audit_logs')
    op.drop_index('ix_rbac_audit_logs_org', table_name='rbac_audit_logs')
    op.drop_index('ix_rbac_audit_logs_target', table_name='rbac_audit_logs')
    op.create_index(op.f('ix_rbac_audit_logs_organization_id'), 'rbac_audit_logs', ['organization_id'], unique=False)
    op.drop_index('ix_valuation_export_logs_task_id', table_name='valuation_export_logs')
    op.create_unique_constraint(None, 'valuation_export_logs', ['task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'valuation_export_logs', type_='unique')
    op.create_index('ix_valuation_export_logs_task_id', 'valuation_export_logs', ['task_id'], unique=False)
    op.drop_index(op.f('ix_rbac_audit_logs_organization_id'), table_name='rbac_audit_logs')
    op.create_index('ix_rbac_audit_logs_target', 'rbac_audit_logs', ['target_user_id'], unique=False)
    op.create_index('ix_rbac_audit_logs_org', 'rbac_audit_logs', ['organization_id'], unique=False)
    op.create_index('ix_rbac_audit_logs_actor', 'rbac_audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_rbac_audit_logs_action', 'rbac_audit_logs', ['action'], unique=False)
    op.alter_column('rbac_audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_pipeline_templates_organization_id'), table_name='pipeline_templates')
    op.drop_index('idx_pipeline_templates_org_default', table_name='pipeline_templates')
    op.create_index('ix_pipeline_templates_org_default', 'pipeline_templates', ['organization_id', 'is_default'], unique=False)
    op.alter_column('pipeline_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('pipeline_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('pipeline_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_pipeline_template_stages_template_id'), table_name='pipeline_template_stages')
    op.create_index('ix_pipeline_template_stages_template', 'pipeline_template_stages', ['template_id'], unique=False)
    op.create_index('ix_pipeline_template_stages_order', 'pipeline_template_stages', ['order_index'], unique=False)
    op.alter_column('pipeline_template_stages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('pipeline_template_stages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.create_index('idx_generated_documents_template_id', 'generated_documents', ['template_id'], unique=False)
    op.create_index('idx_generated_documents_status', 'generated_documents', ['status'], unique=False)
    op.create_index('idx_generated_documents_organization_id', 'generated_documents', ['organization_id'], unique=False)
    op.create_index('idx_generated_documents_created_at', 'generated_documents', ['created_at'], unique=False)
    op.alter_column('generated_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('generated_documents', 'generated_by_user_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('generated_documents', 'organization_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('generated_documents', 'status',
               existing_type=postgresql.ENUM('draft', 'generated', 'finalized', 'sent', name='documentstatus'),
               server_default=sa.text("'generated'::documentstatus"),
               existing_nullable=False)
    op.alter_column('generated_documents', 'variable_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               nullable=False)
    op.alter_column('generated_documents', 'template_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('generated_documents', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.create_index('idx_document_templates_template_type', 'document_templates', ['template_type'], unique=False)
    op.create_index('idx_document_templates_status', 'document_templates', ['status'], unique=False)
    op.create_index('idx_document_templates_organization_id', 'document_templates', ['organization_id'], unique=False)
    op.create_index('idx_document_templates_created_at', 'document_templates', ['created_at'], unique=False)
    op.alter_column('document_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('document_templates', 'created_by_user_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('document_templates', 'organization_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_templates', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=False)
    op.alter_column('document_templates', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'ARCHIVED', name='templatestatus'),
               server_default=sa.text("'ACTIVE'::templatestatus"),
               existing_nullable=False)
    op.alter_column('document_templates', 'variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               nullable=False)
    op.alter_column('document_templates', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_questions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'deal_matches', type_='foreignkey')
    op.drop_index(op.f('ix_deal_matches_organization_id'), table_name='deal_matches')
    op.drop_column('deal_matches', 'organization_id')
    op.alter_column('blog_posts', 'read_time_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('blog_posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('blog_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('blog_posts', 'published',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('blog_posts', 'author',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Dudley Peacock'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_admin_scores_id'), table_name='admin_scores')
    op.alter_column('admin_scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_scores', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_scores', 'activities_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('admin_scores', 'streak_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_prospects_id'), table_name='admin_prospects')
    op.alter_column('admin_prospects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_prospects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_prospects', 'status',
               existing_type=postgresql.ENUM('new', 'qualified', 'engaged', 'proposal', 'negotiation', 'closed_won', 'closed_lost', name='prospectstatus'),
               server_default=sa.text("'new'::prospectstatus"),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_nudges_id'), table_name='admin_nudges')
    op.alter_column('admin_nudges', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_nudges', 'read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('admin_nudges', 'priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='nudgepriority'),
               server_default=sa.text("'normal'::nudgepriority"),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_meetings_id'), table_name='admin_meetings')
    op.alter_column('admin_meetings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_meetings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_meetings', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_lead_captures_id'), table_name='admin_lead_captures')
    op.alter_column('admin_lead_captures', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_lead_captures', 'synced_to_ghl',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_goals_id'), table_name='admin_goals')
    op.alter_column('admin_goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_goals', 'target_calls',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('admin_goals', 'target_videos',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('admin_goals', 'target_emails',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('admin_goals', 'target_discoveries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_focus_sessions_id'), table_name='admin_focus_sessions')
    op.alter_column('admin_focus_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_focus_sessions', 'interrupted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('admin_focus_sessions', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('admin_focus_sessions', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('50'),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_deals_id'), table_name='admin_deals')
    op.alter_column('admin_deals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_deals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_deals', 'probability',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('admin_deals', 'stage',
               existing_type=postgresql.ENUM('discovery', 'qualification', 'proposal', 'negotiation', 'closing', 'won', 'lost', name='admindealstage'),
               server_default=sa.text("'discovery'::admindealstage"),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_content_scripts_id'), table_name='admin_content_scripts')
    op.alter_column('admin_content_scripts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_content_scripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_admin_content_pieces_id'), table_name='admin_content_pieces')
    op.alter_column('admin_content_pieces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_content_pieces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_content_pieces', 'views_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('admin_content_pieces', 'status',
               existing_type=postgresql.ENUM('idea', 'scripting', 'recording', 'editing', 'ready', 'published', name='contentstatus'),
               server_default=sa.text("'idea'::contentstatus"),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_collateral_usage_id'), table_name='admin_collateral_usage')
    op.alter_column('admin_collateral_usage', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_admin_collateral_id'), table_name='admin_collateral')
    op.alter_column('admin_collateral', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_collateral', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_admin_campaigns_id'), table_name='admin_campaigns')
    op.alter_column('admin_campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_campaigns', 'clicked_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('admin_campaigns', 'opened_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('admin_campaigns', 'sent_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('admin_campaigns', 'total_recipients',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('admin_campaigns', 'status',
               existing_type=postgresql.ENUM('draft', 'scheduled', 'sending', 'sent', 'paused', 'cancelled', name='campaignstatus'),
               server_default=sa.text("'draft'::campaignstatus"),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_campaign_recipients_id'), table_name='admin_campaign_recipients')
    op.alter_column('admin_campaign_recipients', 'bounced',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('admin_campaign_recipients', 'clicked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('admin_campaign_recipients', 'opened',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('admin_campaign_recipients', 'sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_activities_id'), table_name='admin_activities')
    op.alter_column('admin_activities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('admin_activities', 'amount',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.create_table('contact_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='contact_messages_pkey')
    )
    op.create_index('ix_contact_messages_id', 'contact_messages', ['id'], unique=False)
    op.create_index('ix_contact_messages_email', 'contact_messages', ['email'], unique=False)
    op.create_index('ix_contact_messages_created_at', 'contact_messages', ['created_at'], unique=False)
    op.drop_index(op.f('ix_document_share_links_share_token'), table_name='document_share_links')
    op.drop_index('idx_share_links_token', table_name='document_share_links')
    op.drop_index('idx_share_links_org_id', table_name='document_share_links')
    op.drop_index('idx_share_links_expires_at', table_name='document_share_links')
    op.drop_index('idx_share_links_document_id', table_name='document_share_links')
    op.drop_table('document_share_links')
    op.drop_table('event_registrations')
    op.drop_table('document_versions')
    op.drop_table('document_ai_suggestions')
    op.drop_table('event_tickets')
    op.drop_table('event_sessions')
    op.drop_table('event_analytics')
    op.drop_index(op.f('ix_community_comments_post_id'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_parent_comment_id'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_author_user_id'), table_name='community_comments')
    op.drop_index('idx_community_comments_post', table_name='community_comments')
    op.drop_index('idx_community_comments_parent', table_name='community_comments')
    op.drop_index('idx_community_comments_created', table_name='community_comments')
    op.drop_index('idx_community_comments_author', table_name='community_comments')
    op.drop_table('community_comments')
    op.drop_table('events')
    op.drop_index(op.f('ix_community_reactions_user_id'), table_name='community_reactions')
    op.drop_index(op.f('ix_community_reactions_target_id'), table_name='community_reactions')
    op.drop_index('idx_community_reactions_user', table_name='community_reactions')
    op.drop_index('idx_community_reactions_unique', table_name='community_reactions')
    op.drop_index('idx_community_reactions_target', table_name='community_reactions')
    op.drop_table('community_reactions')
    op.drop_index(op.f('ix_community_posts_organization_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_author_user_id'), table_name='community_posts')
    op.drop_index('idx_community_posts_status', table_name='community_posts')
    op.drop_index('idx_community_posts_org_id', table_name='community_posts')
    op.drop_index('idx_community_posts_created', table_name='community_posts')
    op.drop_index('idx_community_posts_category', table_name='community_posts')
    op.drop_index('idx_community_posts_author', table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_community_moderation_actions_target_id'), table_name='community_moderation_actions')
    op.drop_index(op.f('ix_community_moderation_actions_moderator_user_id'), table_name='community_moderation_actions')
    op.drop_index('idx_community_moderation_target', table_name='community_moderation_actions')
    op.drop_index('idx_community_moderation_moderator', table_name='community_moderation_actions')
    op.drop_index('idx_community_moderation_created', table_name='community_moderation_actions')
    op.drop_table('community_moderation_actions')
    op.drop_index(op.f('ix_community_follows_organization_id'), table_name='community_follows')
    op.drop_index(op.f('ix_community_follows_following_user_id'), table_name='community_follows')
    op.drop_index(op.f('ix_community_follows_follower_user_id'), table_name='community_follows')
    op.drop_index('idx_community_follows_unique', table_name='community_follows')
    op.drop_index('idx_community_follows_org', table_name='community_follows')
    op.drop_index('idx_community_follows_following', table_name='community_follows')
    op.drop_index('idx_community_follows_follower', table_name='community_follows')
    op.drop_table('community_follows')
    # ### end Alembic commands ###
