"""add_deal_matching_tables_dev_018_phase_1

Revision ID: a0175dfc0ca0
Revises: f1b4a3c0d8c2
Create Date: 2025-10-29 08:26:29.150419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0175dfc0ca0'
down_revision: Union[str, None] = 'f1b4a3c0d8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'deal_match_criteria',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('organization_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('deal_type', sa.String(), nullable=False),
        sa.Column('industries', sa.JSON(), nullable=False),
        sa.Column('min_deal_size', sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column('max_deal_size', sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column('geographies', sa.JSON(), nullable=True),
        sa.Column('structures', sa.JSON(), nullable=True),
        sa.Column('negative_filters', sa.JSON(), nullable=True),
        sa.Column('weights', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_match_criteria_organization_id'), 'deal_match_criteria', ['organization_id'], unique=False)
    op.create_index(op.f('ix_deal_match_criteria_user_id'), 'deal_match_criteria', ['user_id'], unique=False)
    op.create_table(
        'deal_matches',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('deal_id', sa.String(length=36), nullable=False),
        sa.Column('matched_deal_id', sa.String(length=36), nullable=False),
        sa.Column('organization_id', sa.String(length=36), nullable=True),
        sa.Column('match_score', sa.Float(), nullable=False),
        sa.Column('confidence', sa.String(), nullable=False),
        sa.Column('explanation', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['matched_deal_id'], ['deals.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_matches_deal_id'), 'deal_matches', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_matches_matched_deal_id'), 'deal_matches', ['matched_deal_id'], unique=False)
    op.create_index(op.f('ix_deal_matches_organization_id'), 'deal_matches', ['organization_id'], unique=False)
    op.create_table('deal_match_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('action_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['deal_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_match_actions_match_id'), 'deal_match_actions', ['match_id'], unique=False)
    op.create_index(op.f('ix_deal_match_actions_user_id'), 'deal_match_actions', ['user_id'], unique=False)
    op.alter_column('podcast_usage', 'episode_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('podcast_usage', 'episode_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_deal_match_actions_user_id'), table_name='deal_match_actions')
    op.drop_index(op.f('ix_deal_match_actions_match_id'), table_name='deal_match_actions')
    op.drop_table('deal_match_actions')
    op.drop_index(op.f('ix_deal_matches_organization_id'), table_name='deal_matches')
    op.drop_index(op.f('ix_deal_matches_organization_id'), table_name='deal_matches')
    op.drop_index(op.f('ix_deal_matches_matched_deal_id'), table_name='deal_matches')
    op.drop_index(op.f('ix_deal_matches_deal_id'), table_name='deal_matches')
    op.drop_table('deal_matches')
    op.drop_index(op.f('ix_deal_match_criteria_user_id'), table_name='deal_match_criteria')
    op.drop_index(op.f('ix_deal_match_criteria_organization_id'), table_name='deal_match_criteria')
    op.drop_table('deal_match_criteria')
    # ### end Alembic commands ###
