"""Add community platform tables

Revision ID: d47310025be2
Revises: 774225e563ca
Create Date: 2025-11-13 10:28:45.370489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47310025be2'
down_revision: Union[str, None] = '774225e563ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_ai_suggestions', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'document_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('document_templates', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('document_templates', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('document_templates', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('document_versions', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('document_versions', 'document_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('document_versions', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('document_versions', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('generated_documents', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('generated_documents', 'template_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('generated_documents', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    op.alter_column('generated_documents', 'generated_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.db.base.GUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_documents', 'generated_by_user_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('generated_documents', 'organization_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('generated_documents', 'template_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('generated_documents', 'id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_versions', 'created_by_user_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_versions', 'organization_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_versions', 'document_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_versions', 'id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_templates', 'created_by_user_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_templates', 'organization_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_templates', 'id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'created_by_user_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'organization_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'document_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
