"""Add community platform tables

Revision ID: d47310025be2
Revises: 774225e563ca
Create Date: 2025-11-13 10:28:45.370489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd47310025be2'
down_revision: Union[str, None] = '774225e563ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all foreign key constraints temporarily to allow type conversion
    op.execute("ALTER TABLE document_templates DROP CONSTRAINT IF EXISTS document_templates_organization_id_fkey")
    op.execute("ALTER TABLE generated_documents DROP CONSTRAINT IF EXISTS generated_documents_template_id_fkey")
    op.execute("ALTER TABLE generated_documents DROP CONSTRAINT IF EXISTS generated_documents_organization_id_fkey")
    op.execute("ALTER TABLE document_ai_suggestions DROP CONSTRAINT IF EXISTS document_ai_suggestions_document_id_fkey")
    op.execute("ALTER TABLE document_ai_suggestions DROP CONSTRAINT IF EXISTS document_ai_suggestions_organization_id_fkey")
    op.execute("ALTER TABLE document_versions DROP CONSTRAINT IF EXISTS document_versions_document_id_fkey")
    op.execute("ALTER TABLE document_versions DROP CONSTRAINT IF EXISTS document_versions_organization_id_fkey")
    
    # Convert all columns to UUID
    # 1. document_templates
    op.alter_column('document_templates', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='id::uuid',
               existing_nullable=False)
    op.alter_column('document_templates', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='organization_id::uuid',
               existing_nullable=False)
    op.alter_column('document_templates', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='created_by_user_id::uuid',
               existing_nullable=False)
    
    # 2. generated_documents
    op.alter_column('generated_documents', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='id::uuid',
               existing_nullable=False)
    op.alter_column('generated_documents', 'template_id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='template_id::uuid',
               existing_nullable=False)
    op.alter_column('generated_documents', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='organization_id::uuid',
               existing_nullable=False)
    op.alter_column('generated_documents', 'generated_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='generated_by_user_id::uuid',
               existing_nullable=False)
    
    # 3. document_ai_suggestions
    op.alter_column('document_ai_suggestions', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='id::uuid',
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'document_id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='document_id::uuid',
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='organization_id::uuid',
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='created_by_user_id::uuid',
               existing_nullable=False)
    
    # 4. document_versions
    op.alter_column('document_versions', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='id::uuid',
               existing_nullable=False)
    op.alter_column('document_versions', 'document_id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='document_id::uuid',
               existing_nullable=False)
    op.alter_column('document_versions', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='organization_id::uuid',
               existing_nullable=False)
    op.alter_column('document_versions', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=postgresql.UUID(as_uuid=True),
               postgresql_using='created_by_user_id::uuid',
               existing_nullable=False)
    
    # Recreate foreign key constraints
    # Note: organization_id foreign keys are skipped if organizations.id is still VARCHAR
    # They will be recreated in a later migration when organizations.id is converted to UUID
    op.create_foreign_key('generated_documents_template_id_fkey', 'generated_documents', 'document_templates', ['template_id'], ['id'])
    op.create_foreign_key('document_ai_suggestions_document_id_fkey', 'document_ai_suggestions', 'generated_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('document_versions_document_id_fkey', 'document_versions', 'generated_documents', ['document_id'], ['id'], ondelete='CASCADE')
    
    # Try to recreate organization_id foreign keys only if organizations.id is UUID
    op.execute("""
        DO $$ 
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'organizations' 
                AND column_name = 'id' 
                AND udt_name = 'uuid'
            ) THEN
                ALTER TABLE document_templates 
                    ADD CONSTRAINT document_templates_organization_id_fkey 
                    FOREIGN KEY (organization_id) REFERENCES organizations(id);
                    
                ALTER TABLE generated_documents 
                    ADD CONSTRAINT generated_documents_organization_id_fkey 
                    FOREIGN KEY (organization_id) REFERENCES organizations(id);
                    
                ALTER TABLE document_ai_suggestions 
                    ADD CONSTRAINT document_ai_suggestions_organization_id_fkey 
                    FOREIGN KEY (organization_id) REFERENCES organizations(id);
                    
                ALTER TABLE document_versions 
                    ADD CONSTRAINT document_versions_organization_id_fkey 
                    FOREIGN KEY (organization_id) REFERENCES organizations(id);
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_documents', 'generated_by_user_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('generated_documents', 'organization_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('generated_documents', 'template_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('generated_documents', 'id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_versions', 'created_by_user_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_versions', 'organization_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_versions', 'document_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_versions', 'id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_templates', 'created_by_user_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_templates', 'organization_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_templates', 'id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'created_by_user_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'organization_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'document_id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_ai_suggestions', 'id',
               existing_type=app.db.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
