# Workflow Status – M&A Intelligence Platform (ApexDeliver)
# Generated by workflow-init (2025-11-11)

generated: "2025-11-11"
project: "M&A Intelligence Platform (ApexDeliver)"
project_type: "software"
selected_track: "enterprise"
field_type: "brownfield"
workflow_path: ".bmad/bmm/workflows/workflow-status/paths/enterprise-brownfield.yaml"

workflow_status: |
  # Prerequisite: Documentation
  document-project: docs/index.md  # agent: analyst

  # Phase 0: Discovery
  brainstorm-project: optional  # agent: analyst
  research: recommended  # agent: analyst
  product-brief: optional  # agent: analyst

  # Phase 1: Planning
  prd: docs/PRD.md  # agent: pm
  validate-prd: docs/planning/prd-validation.md  # agent: pm
  create-design: docs/ux-design-specification.md  # agent: ux-designer
  framework: optional  # agent: tea
  ci: optional  # agent: tea

  # Phase 2: Solutioning
  create-architecture: docs/architecture.md  # agent: architect
  create-security-architecture: optional  # agent: architect
  create-devops-strategy: optional  # agent: architect
  validate-architecture: optional  # agent: architect
  solutioning-gate-check: docs/implementation-readiness-report-2025-11-10.md  # agent: architect

  # Phase 3: Implementation
  sprint-planning: docs/planning/sprint-planning-phase3.md  # agent: sm
