/**
 * Centralized icon exports to prevent Lucide React initialization issues in production builds
 *
 * Issue: Vite's code splitting was causing "Cannot set properties of undefined (setting 'Activity')"
 * Solution: Re-export all icons from a single module to ensure proper initialization order
 */

// Re-export all icons used in the application
export {
  Activity,
  AlertCircle,
  Archive,
  ArrowLeft,
  ArrowRight,
  Bell,
  Briefcase,
  Building2,
  Calendar,
  CalendarIcon,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  Edit2,
  ExternalLink,
  Eye,
  FileText,
  Filter,
  Flame,
  Home,
  LayoutDashboard,
  LayoutGrid,
  Linkedin,
  List,
  Loader2,
  LucideIcon,
  Mail,
  Menu,
  Mic,
  Moon,
  MoreVertical,
  MousePointer,
  Newspaper,
  Pause,
  Phone,
  Play,
  Plus,
  Search,
  Send,
  Settings,
  SortAsc,
  Square,
  Sun,
  Tag,
  Target,
  Trash2,
  TrendingUp,
  Twitter,
  UploadCloud,
  User,
  Users,
  X,
  XCircle,
  Youtube,
  Zap,
} from 'lucide-react'

export type { LucideIcon } from 'lucide-react'
